---
title: "Snow algae 2018 map"
---

```{r libs}
library(tidyverse)
library(here)
library(lubridate)
library(ggmap)
library(ggdark) # ggplot themes
library(googleway) # for getting geographic data from google
library(ggsn) # add symbols to plot
```

```{r data_in}
field <- read_csv(here::here("data/02_tidied/tidied_field.csv"))
```

```{r settings}
key=
register_google(key = key)
```


```{r map_setup}
algae_map <- get_googlemap(c(-123.004722, 49.850556), zoom = 7, maptype = "satellite")

# add in Vancouver and Squamish
cities <- c("Vancouver, BC, Canada", "Squamish, BC, Canada")
# get coordinates from google
google_output <- cities %>% 
  map(~googleway::google_geocode(.x, key=key))
glimpse(google_output)

# functions to reach into the list and extract wanted elements
city_name <- function(x) x$results$address_components[[1]][1,2]
lat <- function(x) x$results$geometry$location[1,1]
lon <- function(x) x$results$geometry$location[1,2]

# make tbl with city and coords
city_coords <- google_output %>% {
  tibble(
    name = map_chr(., .f=city_name),
    lat = map_dbl(., .f=lat),
    lon = map_dbl(., .f=lon)
  )
}
```

```{r all_samples_map}
full_map <- ggmap(algae_map, extent = "device") +
  # jitter points to make it easier to read
  geom_jitter(data = field, 
              size = 2, alpha=0.5, 
              width = 0.05, height = 0.05, # specify jitter
              aes(color=elev_m)) +
  scale_color_gradientn(colours = terrain.colors(8)[1:7], limits = c(850,2200)) +
  geom_point(data = city_coords, shape = 15) +
  geom_text(data = city_coords, aes(label = name), hjust = 1.1)+
  labs(title = "Snow algae sample sites, summer 2018", color="Elevation (m)") 

full_map
```

```{r plot_function}
plot_map <- function(my_month){
  # input: chr with capitalized complete month name, eg "May","June"
  # output: ggplot showing the location of samples from that month
  filtered_sample_coords <- field %>% 
    filter( lubridate::month(date, label=TRUE, abbr=FALSE) == my_month)
  
  ggmap(algae_map, extent = "device") +
    # jitter points to make it easier to read
    geom_jitter(data = filtered_sample_coords, 
                size = 2, alpha=0.7, 
                width = 0.05, height = 0.05, # specify jitter
                aes(color=elev_m)) +
    scale_color_gradientn(colours = terrain.colors(8)[1:7], limits = c(850,2200)) +
    geom_point(data = city_coords, shape = 15) +
    geom_text(data = city_coords, aes(label = name), hjust = 1.1)+
    labs(title = my_month, color="Elevation (m)")}

#test
plot_map("May")
```

```{r save_maps}
save_map <- function(my_month, num){
  map <- plot_map(my_month)
  
  ggsave(filename = here::here("figs","map",paste0("map_",num,"_", my_month,".png")),
       plot = map, height = 15, width = 20, units = "cm")
}

# generate plots
save_map("May",1)
save_map("June",2)
save_map("July",3)
save_map("August",4)
save_map("September",5)

ggsave(filename = here::here("figs","map",paste0("full_map.png")),
       plot = full_map, height = 15, width = 20, units = "cm")


```

