---
title: "Cellct analysis"
output: html_notebook
---

```{r, include=F}
library(tidyverse)
library(here)
library(gridExtra)
```

```{r, include=F}
cellct <- read_csv(here("data/02_tidied/tidied.cell_count.csv"))
field <- read_csv(here("data/02_tidied/tidied_field.csv"))
rel_abund <- read_csv(here("data/03_filtered/rbcl/filtered_cleaned_rbcl_rel_abund.csv"))
```

```{r heatmap, echo=F, fig.height=5, fig.width=6}
cellct_tbl <- cellct %>% 
  left_join(field, by="sample_id")

distinct(cellct_tbl, sample_id) %>% nrow()
```

Heatmap for figure 4
```{r, echo=F, fig.height=5, fig.width=6}

cellct_tbl_w_seq <- cellct_tbl %>% 
  filter(sample_id %in% samples_w_seq)

samples_w_seq ## not sure where this comes from
samples_with_cellcounts <- cellct_tbl_w_seq %>% distinct(sample_id) %>% pull(sample_id)
setdiff(samples_w_seq, samples_with_cellcounts) # missing these


cellct_tbl_w_seq %>% distinct(sample_id)
cellct_tbl_w_seq %>% distinct(morpho_sp)

my_theme <- theme(axis.text.x = element_text(angle = 45, hjust = 1))

cellct_ord <- c("Chlainomonas rubra","Sanguina nivaloides","Chloromonas krienitzii","Chloromonas cf. brevispina","Chloromonas cf. nivalis", "Green cell","Other")

cellct_tbl_w_seq %>% distinct(sample_id) %>% nrow()

cellct_heatmap <- ggplot(cellct_tbl_w_seq, 
                         aes(y=alias %>% fct_reorder(elev_m), 
                             x=morpho_sp %>% fct_relevel(cellct_ord))) +
  geom_tile(aes(alpha = percent_of_sample, fill = morpho_sp %>% fct_relevel(cellct_ord))) +
  labs(x="Cell morphology", y= "Elevation") +
  scale_alpha(range = c(0.1, 1)) +
  my_theme +
  guides(alpha="none",fill="none")

cellct_heatmap
```


```{r, echo=F, fig.height=5, fig.width=6}

my_theme <- theme(axis.text.y=element_blank(),
                  axis.ticks.y=element_blank())


p2 <- p %>% 
 filter(!(morpho_sp %in% c("Other","Green cell")))
cellct_scatter <- ggplot(p2, aes(x=date, y=elev_m)) +
  geom_jitter(aes(color=morpho_sp, size=percent_of_sample), alpha=0.5, width = 10, height=10) +
  scale_size(range=c(0.5, 10)) +
  labs(color="Morphospecies",size="Relative abundance",y="Elevation (m)",x="Date") +
  guides(colour = guide_legend(override.aes = list(alpha = 1, size=3))) +
  ggthemes::theme_few()
cellct_scatter

# pie charts?
```

```{r elevation_bar, echo=F, fig.height=5, fig.width=1}
elevation_ranges <- short_names %>% 
  distinct(elev_m, sample_id) %>% 
  arrange(elev_m)

my_theme <- theme(axis.title.x =element_blank(),
                  axis.text.x=element_blank(),
                  axis.ticks.x=element_blank(),
                  axis.title.y =element_blank(),
                  axis.text.y=element_blank(),
                  axis.ticks.y=element_blank(),
                  panel.grid.major = element_blank(),
                  panel.grid.minor = element_blank(),
                  panel.background = element_blank(),
                  legend.position = "none")

elev <- ggplot(elevation_ranges, aes(x=sample_id %>% fct_reorder(elev_m), y=2200-elev_m, fill=elev_m))+
  geom_bar(width=1, stat = "identity")+
  scale_fill_gradientn(colors = terrain.colors(8)[1:7]) +
  coord_flip() +
  my_theme +
  # labs(y="Elevation (m)")
  annotate(geom="text", x=3, y=500, label="800 m",
              color="black") +
  annotate(geom="text", x=115, y=500, label="2200 m",
              color="black")
  
elev
```

```{r}
cellct_in_seq <- short_names %>% 
  filter(have_seq==T)

cust_theme <- theme(legend.position = "none",
                    panel.grid.major.x = element_blank(), # remove vertical lines in background
                    panel.grid.minor.x = element_blank(),
                    axis.line=element_blank(), # remove x axis
                    axis.title.x=element_blank(), 
                    axis.text.x=element_blank(),
                    axis.ticks.x=element_blank(),
                    panel.spacing = unit(-0.01, "lines"), # remove space between facet panels
                    # strip.text.x = element_text(angle = 0, hjust=1.0, vjust = 0.8), # rotate facet labels 90
                    strip.background = element_blank()) # remove grey boxes around facet labs


cellct_order <- c("Cr","Sn","Cb","Ck","Cn","G","O")

cellct_in_seq_bar <- ggplot(cellct_in_seq, aes(x=alias %>% fct_reorder(elev_m), y=percent_of_sample)) +
  geom_bar(aes(fill=short_morpho_name), stat="identity") + # classic stacked relative abundance plot
  coord_flip() +
  facet_grid(~short_morpho_name, switch = "x") +
  labs( x="Sample ID", tag="B") +
  cust_theme

cellct_in_seq_bar
```



```{r}
# dir.create(here("manuscript/figs/supp/cellct"))
ggsave(filename=here("manuscript/figs/supp/cellct/cellct_dotplot.pdf"), plot=cellct_scatter, height = 5, width = 6)
ggsave(here("manuscript/figs/supp/cellct/elevations.pdf"), plot=elev, height=7, width=1)


saveRDS(cellct_heatmap, here("output/cellct_w_seq_heatmap.Rda"))
```

