---
title: "Generate sample aliases"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
path <- here("data/clean/field_clean.csv")
field <- read_csv(path)
```
Give each mountain a unique letter ID
```{r}
field_1 <- field %>% 
  select(sample_id, elev_m, date) %>% 
  mutate(mountain = str_sub(sample_id,0,3)) 
field_1 %>% 
  distinct(mountain) %>% 
  arrange(mountain)
```

Sax =X, Sey=S, Sky=K, and Stm=M
```{r}
field_2 <- field_1 %>% 
  mutate(mountain_letter = case_when(mountain == "sax"~"X",
                                     mountain == "sey"~"S",
                                     mountain == "sky"~"K",
                                     mountain == "stm"~"M",
                                     TRUE ~ str_sub(mountain, 0,1) %>% toupper()))
field_2
```

Now give each sample a unique identifier by date
```{r}
sample_dates <- field_2 %>%
  distinct(date) %>% 
  arrange(date) %>% 
  rownames_to_column("date_ord")

field_3 <- field_2 %>% 
  left_join(sample_dates, by="date")

field_3 %>% select(date_ord, date)
```

Add a decimal for samples collected at the same date
```{r}
# split df by date, order each date by elevation going down, then add this as decimal to the alias
alias_tbl <- field_3 %>% 
  mutate(alias = paste0(mountain_letter, date_ord)) %>% 
  arrange(alias, -elev_m) %>% 
  group_by(alias, add = T) %>% 
  group_split(alias) %>% 
  map(rownames_to_column) %>% 
  reduce(bind_rows) %>%
  ungroup() %>% 
  mutate(alias = paste0(alias, ".",rowname)) %>% 
  select(sample_id, alias)
```

```{r}
path_to_write <- here("data/sample_aliases.csv")
write_csv(alias_tbl, path_to_write)
```

