---
title: "not_used"
author: "Casey Engstrom"
date: "21/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

trouble getting anything useful out of ggsn::scalebar()
```{r}
  ggmap(algae_map, extent = "device") +
    # jitter points to make it easier to read
    geom_jitter(data = field, 
                size = 2, alpha=0.7, 
                width = 0.05, height = 0.05, # specify jitter
                aes(color=elev_m)) +
    scale_color_gradientn(colours = terrain.colors(8)[1:7], limits = c(850,2200)) +
    geom_point(data = city_coords, shape = 15) +
    geom_text(data = city_coords, aes(label = name), hjust = 1.1)+
    labs(title = "my_month", color="Elevation (m)")+
    scalebar(x.min = -123, x.max = -124,
             y.min = 48, y.max = 50,
             dist = 50, dist_unit = "km",
             height = 0.05,
             st.bottom = FALSE, st.color = "white",
             box.color = "white",
             transform = TRUE, model = "WGS84",
             vjust = -0.5, size=0.5)
```
