---
title: "18S algae ASV clustering"
output: pdf_document
---

```{r, include=F}
library(tidyverse)
library(DECIPHER)
library(ape)
library(ggtree)
library(gridExtra)
library(ggpubr)
library(cowplot)
```

```{r, include=F}
aligns <- readDNAStringSet(here::here("data/fastas/asv_seq_data/algae_18s_quality_aligns.fasta"))
# taxonomy w genbank (multiple copies of each designation, no editing)
taxonomy <- read_csv(here::here("data/taxonomy/algae_18s_assignments_snow_algae_genbank.csv"))
tree <- ape::read.tree(here::here("data/tree/algae_18s/algae_18s_seqs.fasta.treefile"))
rel_abund <- read_csv(here::here("data/rel_abund/3_filter/18s_algae/18s_algae_rel_abund.csv")) 

# get total rel abund
total_rel_abund <- rel_abund %>% 
  group_by(asv_id) %>% 
  summarise(rel_abund = sum(rel_abund))

```


```{r, include=F}
# BrowseSeqs(aligns, highlight = T)

dists <-  aligns %>% 
  DECIPHER::DistanceMatrix(type="matrix", correction = "JC")
```

# MDS
```{r mds, echo=F, message=F, warning=F}
set.seed(123)
mds_coords <- dists %>% 
  cmdscale() %>% # ok to use euclidian dist, no null values when comparing relatedness
  as_tibble() %>% 
  add_column(asv_id = colnames(dists), .before=1)

mds_coords_w_taxonomy <- mds_coords %>% 
  left_join(taxonomy, by="asv_id") %>% 
  left_join(rel_abund, by="asv_id")

colors <- c("Sanguina_nivaloides"="#ff534a",
            "Chloromonas_asteroidea"="#80c786", 
            "Chloromonas_nivalis"="#4aaf86", 
            "Chloromonas"="#4aaf53", 
            "Trebouxiophyceae"="#975c5c", 
            "Trebouxia"="#975c5c", 
            "Koliellaceae"="#975c5c",
            "Chlamydomonas_proboscigera"="grey60", 
            "Chlorogonium"="grey60", 
            "Chlamydomonadaceae"="grey60",
            "Chlamydomonadales"="grey60",
            "NA"="grey60")

mds_1 <- ggplot(mds_coords_w_taxonomy, aes(x=V1, y=V2))+
  geom_point(aes(color=best_assignment, size=rel_abund), alpha=0.7, na.rm=TRUE) +
  scale_color_manual(values= colors) +
  guides(size="none",
         colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  # include pts not assigned taxonomy
  geom_point(data = filter(mds_coords_w_taxonomy, is.na(best_assignment)), 
             color = "grey", alpha = 0.8) +
  labs(color="Taxonomic assignment", tag="A")

legend <- mds_1 %>% 
  cowplot::get_legend() %>% 
  ggpubr::as_ggplot()

mds <- mds_1 +
  theme(legend.position = "none")
  
```


# t-SNE
```{r, echo=F,message=F, warning=F}
perplexity <- 20

set.seed(123)
tsne_full_output <- dists %>% 
  Rtsne::Rtsne(pca=F, perplexity = perplexity)

tsne_pts <- tsne_full_output$Y %>% 
  as_tibble()

tsne_pts_taxonomy <- tsne_pts %>% 
  add_column(asv_id = colnames(dists)) %>% # label each point by it's ASV ID
  left_join(taxonomy, by="asv_id") %>% 
  left_join(rel_abund, by="asv_id")

tsne <- ggplot(tsne_pts_taxonomy, aes(x=V1, y=V2)) +
  geom_point(data = tsne_pts_taxonomy, 
             aes(color = best_assignment, size=rel_abund), 
             alpha = 0.8, na.rm=TRUE) +
  # include points not assigned to genus or species
  geom_point(data = filter(tsne_pts_taxonomy, is.na(best_assignment)), 
             color = "grey", alpha = 0.8) +
  scale_color_manual(values= colors) +
  guides(size="none",
         colour = guide_legend(override.aes = list(size=5, alpha=1))) +
  labs(color="Taxonomic assignment", tag="B") +
  theme(legend.position = "none")
  
```



```{r, echo=F, message=F, warning=F}

# re-root tree
root <- taxonomy %>% 
  filter(class=="Trebouxiophyceae") %>% 
  head(1) %>% 
  pull(asv_id)

tree <- tree %>% root(outgroup = root, resolve.root=T)

ggtree_18s <- ggtree(tree)


# format bayesian/bootstrap confidence for each node
boots <- ggtree_18s$data %>% 
  filter(isTip == FALSE) %>% 
  separate(label, c("boot", "bayes"), sep = "/") %>% #split label into boots and bayes vals
  filter(boot > 80) %>%
  mutate(boot = round(as.numeric(boot), digits = 0),
         insignificant_edge = if_else(boot > 80, "black", "red"))# round boot to nearest integer

annotate <- ggtree_18s$data %>% 
  left_join(total_rel_abund, by=c("label"="asv_id")) %>% 
  left_join(taxonomy, by=c("label"="asv_id"))

colors <- c("Sanguina_nivaloides"="#ff534a",
            "Chloromonas_asteroidea"="#80c786", 
            "Chloromonas_nivalis"="#4aaf86", 
            "Chloromonas"="#4aaf53", 
            "Trebouxiophyceae"="#975c5c", 
            "Trebouxia"="#975c5c", 
            "Koliellaceae"="#975c5c",
            "Chlamydomonas_proboscigera"="grey60", 
            "Chlorogonium"="grey60", 
            "Chlamydomonadaceae"="grey60",
            "Chlamydomonadales"="grey60",
            "NA"="grey60")

tree_out <- ggtree(tree) +
  geom_text2(data=boots, aes(label=paste0(boot,";",bayes)),  vjust= 0.01, hjust = 1, size=2) +
  geom_tippoint(data = annotate, aes(color= best_assignment, size=rel_abund), alpha=1, na.rm=TRUE) + 
  theme(legend.position = c(0.89,0.7),
        legend.title = element_blank(),
        legend.key = element_blank()) +
  scale_color_manual(values= colors) +
  geom_tiplab(data = annotate, aes(label = best_assignment), size=2)+
  guides(size="none") +
  labs(tag="C") +
  theme(legend.position = "none")
```



```{r, fig.width=8, fig.height=10}
lay <- rbind(c(1,1,4),
             c(2,2,4),
             c(3,3,4),
             c(3,3,4),
             c(3,3,4))
gridExtra::grid.arrange(mds, tsne, tree_out, legend, layout_matrix=lay)


```

