---
title: "PCR Conditions"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

We constructed our amplicon library using a two-step PCR. In the first PCR we amplified template DNA using our primers attached to a universal adapter, and in the second PCR we re-amplified that product to attach a 6 bp index to the universal adapter at the 3’ end. The first PCR total volume was 25 $\mu$L, consisting of 1 $\mu$L template, 12.5 $\mu$L Q5 high-fidelity 2X Master Mix (New England BioLabs), 1.25 $\mu$L each of forward and reverse primer, and 9 $\mu$L of ddH2O. The second PCR was the same except we reduced our reaction volume to 20 $\mu$L by using only 5 $\mu$L of ddH2O. The cycling conditions were the same for both primer pairs for the first PCR, with an initial denaturation at 98 $^\circ$C for 30 s, followed by 30 cycles of 98 $^\circ$C for 5 s, 58 $^\circ$C for 10 s, and 72 $^\circ$C for 25 s, with a final extension at 72 $^\circ$C for 2 minutes. For the second indexing PCR we started with an initial denaturation at 98 $^\circ$C for 30 s, then 10 cycles of 98 $^\circ$C for 10 s, 65 $^\circ$C for 30 s, and 72 $^\circ$C for 30 s with a final denaturation of 72 $^\circ$C for 5 min.